services:
  api:
    container_name: mlops-exam-1-backend
    image: jonohas/mlops-exam-1-backend
    build:
      context: api

    ports:
      - "3000:80"

    expose:
      - "80"

    

  frontend:
    container_name: mlops-exam-1-frontend
    image: jonohas/mlops-exam-1-frontend
    build: frontend
    ports:
      - "8080:80"
    environment:
      - API_HOST=api
      - API_PORT=80
