services:
  api:
    build:
      context: api

    ports:
      - "3000:80"

    expose:
      - "80"

    

  frontend:
    build: frontend
    ports:
      - "8080:80"
    environment:
      - API_HOST=api
      - API_PORT=80
