apiVersion: v1
kind: Service
metadata:  
  namespace: mlops-exam
  name: frontend-nodeport-service
spec:
  selector:    
    app: mlops-exam-frontend
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30001
    protocol: TCP