apiVersion: v1
kind: Service
metadata:  
  namespace: mlops-exam
  name: backend-nodeport-service
spec:
  selector:    
    app: mlops-exam-backend
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30000
    protocol: TCP