name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Build the API image
      run: docker build api --tag mlops-exam-1-backend:${{ github.sha }}
    - name: Build the Frontend image
      run: docker build frontend --tag mlops-exam-1-frontend:${{ github.sha }}
